### ISSUE TITLE
Pose Normalization Issue

### ISSUE THREAD

**Issue by RegisWu** [Blade6570/icface#10]
This is a very interesting work! 

I am wondering why you normalize the pose attribute with (p + 0.7) /1.4. Could you please explain more about it?

https://github.com/Blade6570/icface/blob/75f9e27c64daa52fc639a79086124cfc78c903e1/test_code_released_new/data/aligned_dataset.py#L47

**Comment by Blade6570** [comment]
Hi, 
This is min-max normalization. the pose values are mostly in between -0.7 to 0.7.

**Comment by RegisWu** [comment]
Noted with thanks!
