### ISSUE TITLE
possible not to use driver video

### ISSUE THREAD

**Issue by ak9250** [Blade6570/icface#4]
can you use a driver image instead of video that is outside the test dataset? For example a input image with a smile expression and a output image with the same smile expression?

**Comment by Blade6570** [comment]
Hi, yes you can use that. You only need the action units of that image and feed it to the network with the source image.

**Comment by ak9250** [comment]
are there flags to specificy to get a image result instead of a video?

**Comment by yanjunma** [comment]
Blade6570 - can you elaborate a bit more on how to extract the action units? I looked up your suggestion of using Openface.  I am not family with Openface but it seems to be fairly complicated as Openface can do a lot of other things. I wonder if there is a simpler way to extract obtain the csv file?  Thanks!

**Comment by yanjunma** [comment]
sorry - just saw you answered the question already in another comment. will check it out first. Thanks.
