### ISSUE TITLE
elaboration on opecface

### ISSUE THREAD

**Issue by fzhang612** [Blade6570/icface#5]
Could you please elaborate on how to "extract the action units in a .csv file using **Opecface**"? I tried to google Opecface and nothing meaningful comes out. 

Many thanks.

**Comment by Blade6570** [comment]
Hi, you can have a look at this link: https://github.com/TadasBaltrusaitis/OpenFace/wiki/Unix-Installation
It has all the API calls examples and also have instructions on how to install in linux/ windows. This is the repo that I have used.

**Comment by fzhang612** [comment]
I see, many thanks for the info. So it should be Ope**n**face, not Ope**c**face
